DX-2705
Bandwidth/node-voice pull request #61
Opened 2022-08-01 19:57 UTC by brianluisgomez

2022-08-01 22:04 UTC, ajrice6713 approved these changes

2022-08-03 17:24 UTC, ajrice6713 approved these changes

2022-08-04 14:57 UTC, bpateldx requested changes

2022-08-04 14:57 UTC, bpateldx commented on src/bxml/startStream.ts
> +    destination: string
If `destination` is required, we are not throwing any error from constructor. Not sure if the auto-generated code has bug or something we missed in the spec!

2022-08-04 14:57 UTC, bpateldx commented on tests/bxml.test.js
> +            var startStream = new StartStream({
Test for `tracks` attribute

2022-08-10 22:14 UTC, bpateldx approved these changes

2022-08-29 19:49 UTC, merged